---
- name: Set your Magento repo global config using composer
  command: composer global config http-basic.repo.magento.com "{{ repo_api_key }}" "{{ repo_secret_key }}"

- name: remove files in html
  command: rm -rf /var/www/html/*

- name: Create the Magento project using composer
  command: composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /var/www/html

- name: Install Magento
  shell: |
    php bin/magento setup:install \
    --base-url="{{ magento_domain }}" \
    --db-host="{{ magento_db_host }}" \
    --db-name="{{ magento_db_name }}" \
    --db-user="{{ magento_db_user }}" \
    --db-password="{{ magento_db_password }}" \
    --backend-frontname="{{ magento_admin_location }}" \
    --admin-firstname="{{ magento_admin_first }}" \
    --admin-lastname="{{ magento_admin_last }}" \
    --admin-email="{{ magento_admin_email }}" \
    --admin-user="{{ magento_admin_user }}" \
    --admin-password="{{ magento_admin_pass }}" \
    --language="{{ magento_language }}" \
    --currency="{{ magento_currency }}" \
    --timezone="{{ magento_timezone }}" \
    --use-rewrites="{{ magento_rewrite }}" \
    --use-secure="{{ magento_secure }}" \
    --use-secure-admin="{{ magento_secure_admin }}" \
    --session-save="{{ magento_session }}"
  args:
    chdir: /var/www/html/
