---
- name: Install Mariadb
  yum:
    name: "{{ item }}"
    state: present
    #    enablerepo: epel
  with_items:
   - mariadb-server
   - libselinux-python
   - libsemanage-python

- name: Start Mariadb Service
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create DB user for Magento
  mysql_user:
    name: "{{ magento_db_user }}"
    password: "{{ magento_db_password }}"
    priv: '*.*:ALL'
    state: present

- name: Create DB schema for Magento
  mysql_db:
    name: "{{ magento_db_name }}"
    state: present
